version: '3.3'

services:
    webApi:
        image : 
            localhost:5000/test/testproject-webgapi:2023-7-24-v1
        ports:
            - "5010:5000"
        networks : 
            - webNetwork
        restart: always
        env_file : webapi.env
        volumes:
            - /volumes/TestProjectFiels/images:/app/wwwroot/images/
            - /volumes/TestProjectFiels/fonts:/app/wwwroot/fonts/
        depends_on:
            - webApi2Service
    webApi2Service:
        image : 
            localhost:5003/test/testproject-webgapi2:2023-7-24-v1
        networks : 
            - webNetwork
        restart: always
        ports:
            - "5011:5003"
        env_file: webapi2.env
    angular:
        image : 
            localhost:5000/test/testproject-angular:2023-7-24-v1
        ports:
            - "4200:80"
        networks : 
            - webNetwork
        restart: always
        env_file : angular.env
    angularTest:
        image : 
            localhost:5000/test/testproject-angular-test:2023-7-24-v1
        ports:
            - "4201:80"
        networks : 
            - webNetwork
        restart: always
networks:
    webNetwork :
        driver: bridge




# version: '3.3'

# services:
#     webApi:
#         image : 
#             localhost:5000/test/testproject-webgapi:2023-7-24-v1
#         ports:
#             - "5010:5000"
#         networks : 
#             - webNetwork
#         restart: always
#         env_file: webapi.env
#         volumes: // bind mount
#             - /volumes/TestProjectFiels/images:/app/wwwroot/images/
#             - testData:/app/wwwroot/fonts/
#     angular:
#         image : 
#             localhost:5000/test/testproject-angular:2023-7-24-v1
#         ports:
#             - "4200:80"
#         networks : 
#             - webNetwork
#         restart: always
#         env_file : angular.env
#     angularTest:
#         image : 
#             localhost:5000/test/testproject-angular-test:2023-7-24-v1
#         ports:
#             - "4201:80"
#         networks : 
#             - webNetwork
#         restart: always
# networks:
#     webNetwork :
#         driver: bridge

# volumes:
#     testData:
        
